targets:
  $default:
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/graphql_api.dart
              schema: lib/gql/schema.graphql
              queries_glob: lib/gql/**.gql
          generate_helpers: true

